export const LOAD_CONTRIBUTORS = 'boilerplate/App/LOAD_CONTRIBUTORS';
export const LOAD_CONTRIBUTORS_SUCCESS = 'boilerplate/App/LOAD_CONTRIBUTORS_SUCCESS';
export const LOAD_CONTRIBUTORS_ERROR = 'boilerplate/App/LOAD_CONTRIBUTORS_ERROR';
